# -*- coding: utf-8 -*-
"""게시판 페이징하기.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCrLJqQa1Ff8mnatwpa8w-A69f5W8ysX
"""

from google.colab import drive
drive.mount('/content/drive')

from IPython.display import Image

Image('/content/drive/MyDrive/Colab Notebooks/abc.PNG')

def getTotalPage(m,n):
  return m//n+1

# m은 총 건수. n은 한 페이지당 보여 줄 건수

print(getTotalPage(5,10))
print(getTotalPage(15, 10))   # 2 출력
print(getTotalPage(25, 10))   # 3 출력
print(getTotalPage(30, 10))  # 3이 출력되어야 하는데 4가 출력

"""나머지값이 0이 될 때 에러가 발생한다. 

-> 수정필요
"""

def getTotalPage(m,n):
  if m%n==0:
    return m//n

  else:
    return m//n+1

print(getTotalPage(5,10))
print(getTotalPage(15, 10))   # 2 출력
print(getTotalPage(25, 10))   # 3 출력
print(getTotalPage(30, 10))  # 3이 출력수정 완료