# -*- coding: utf-8 -*-
"""3과 5의 배수 합하기.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17h5TzDGhkZbAP8Go7QVFxK9531ra34AC

10 미만의 자연수에서 3과 5의 배수를 구하면 3, 5, 6, 9이다. 이들의 총합은 23이다.   
1000 미만의 자연수에서 3의 배수와 5의 배수의 총합을 구하라.
"""

# way1 (내 풀이)

sum=0

for i in range(1,1000):

  if i%3 == 0:
    sum+=i
  
  elif i%5==0:
    sum+=i

  else:
    pass
  
print(sum)

# way2

result = 0
for n in range(1, 1000):
    if n % 3 == 0 or n % 5 == 0: 
        result += n
print(result)

"""이 문제에는 한 가지 함정이 있는데 3으로도 5로도 나누어지는 15와 같은 수를 이중으로 더해서는 안 된다는 점이다.
   
따라서 15와 같이 3의 배수도 되고 5의 배수도 되는 값이 이중으로 더해지지 않기 위해 or 연산자를 사용하였다.
"""